#!/usr/bin/perl

$flag=0;

while(<>){

if(/\<head\>/){
	$flag=1;
	print;
	next;
}


if(/\<\/head\>/ and $flag){

	$flag=0;

print 
"<script type=\"text/x-mathjax-config\">
   MathJax.Hub.Config({tex2jax: {inlineMath: [['\$','\$'], ['\\\\(','\\\\)']]}}); </script>
    <script src=\"http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML\" type=\"text/javascript\">
     </script>
<script type='text/javascript' src='/ServPak/js/jquery.js'></script>
<script type='text/javascript' src='/ServPak/js/mathformat.js'></script>
<link rel='stylesheet' type='text/css' href='/ServPak/css/math.css'/>
<script type=\"text/javascript\">
    document.captureEvents(Event.KEYDOWN);
    document.onkeydown = goKey;
        function goKey(e) {
        var y = String.fromCharCode(e.which);
        if(y==\"B\"){
                e.stopPropagation();
                e.preventDefault();
                history.back();
        }
     }
</script>
</head>
";
next;

}

print;
}
