#!/usr/bin/perl

$name = shift;

open(IN,$name);
open(OUT1,">tempgraph");
select OUT1;

while (<IN>) {
@line=split(/:|\&|\s+/,$_);

if ($line[8] eq "F.") { next;}
if ($line[11] eq "inches") {next;}
if ($line[11] eq "") { next;}

@x = ($line[3],$line[8]);

$maxtime = $x[0] unless $maxtime;
if ($x[0] > $maxtime) { $x[0] -=24;}


$Temp = $line[8]; 
$Pres = $line[11];

$mintemp = $line[8] unless $mintemp; $mintemp = $mintemp > $line[8]? $line[8]:$mintemp;
$maxtemp = $line[8] unless $maxtemp; $maxtemp = $maxtemp < $line[8]? $line[8]:$maxtemp;

$minpres = $line[11] unless $minpres; $minpres = $minpres > $line[11]? $line[11]:$minpres;
$maxpres = $line[11] unless $maxpres; $maxpres = $maxpres < $line[11]? $line[11]:$maxpres;


$totTemp += $Temp;
$totPres += $Pres; 

$sqsumTemp += $Temp*$Temp;
$sqsumPres += $Pres*$Pres;

$num++;




for (@x) { 
print;print "\t";

}
print "\n";
}

close IN;close OUT1;

print "\n\n";

$avgTemp = $totTemp/$num;
$avgPres = $totPres/$num;

$avgsqsumTemp = $sqsumTemp/$num;
$avgsqsumPres = $sqsumPres/$num;

$varTemp = $avgsqsumTemp - ($avgTemp**2);
$varPres = $avgsqsumPres - ($avgPres**2);

$stdTemp = substr(sqrt($varTemp+0.000001),0,4);
$stdPres = substr(sqrt($varPres+0.000001),0,4);

$avgTemp = substr($avgTemp,0,5);
$avgPres   = substr($avgPres,0,5);

open(IN2,$name);
open(OUT2,">pressgraph");
select OUT2;

while (<IN2>) {
@line=split(/:|\&|\s+/,$_);

if ($line[8] eq "F.") { next;}
if ($line[11] eq "inches") {next;}
if ($line[11] eq "") {next;}

@x = ($line[3],$line[11]);

$maxtime = $x[0] unless $maxtime;
if ($x[0] > $maxtime) { $x[0] -=24;}

for (@x) { 
print;print "\t";

}
print "\n";
}
close IN2;close OUT2;

$tempstep = $stdTemp/2;
$presstep = $stdPres/2;

$mintemp -= $tempstep; $maxtemp += $tempstep;
$minpres -= $presstep; $maxpres += $presstep;

`/usr/bin/graph -T png --bitmap-size 480x480 -Y "Temperature" -X "Time" -L "Temperature over the last 24 hours" -y  $mintemp $maxtemp $tempstep < tempgraph > temp.png`;
`/usr/bin/graph -T png --bitmap-size 480x480 -Y "Pressure" -X "Time" -L "Pressure over the last 24 hours" -y  $minpres $maxpres $presstep < pressgraph> pres.png `;
 
