<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Weather at Carbondale</title>
<style type="text/css">

 td.x { 
 font-family: helvetica; font-size: 130%;
}

 td.big {
 font-family: helvetica; font-size: 143%;
}

 td {
 font-family: helvetica;
}

 th {
 font-weight: normal;
}

</style>
</head>
<body bgcolor="f0ffff">
<h1><em><font color="darkblue">Weather at Carbondale</font></em></h1>
<?

%longday=("Mon"=&gt;"Monday","Tue"=&gt;"Tuesday","Wed"=&gt;"Wednesday",
	  "Thu"=&gt;"Thursday","Fri"=&gt;"Friday","Sat"=&gt;"Saturday","Sun"=&gt;"Sunday");
@date = split(/\s+/,scalar localtime);
print '<font style="background:white"> Today is ';
print "$longday{$date[0]}, $date[1] $date[2] <br>The time is now $date[3] <p></p></font>";


!>
<table>
<tr>
<td align="left" class="x">
<i>Current Weather: </i><img height="0" width="50"><b>Fair</b>
</td>
<td><img src="WeathIcons/dust.jpg"></td>
</tr>
<tr>
<td><table bgcolor="ffffee">
<tr><td align="left" class="big">Date: 
&#160;Jan 14</td></tr>
<tr><td align="left" class="big">Time: 
&#160;16:08:01</td></tr>
<tr><td align="left" class="big">Wind: 
&#160;From the Northwest at 13 MPH</td></tr>
<tr><td align="left" class="big">Visibility: 
&#160;10.00 mi.</td></tr>
<tr><td align="left" class="big">Temperature: 
&#160;24 F.</td></tr>
<tr><td align="left" class="big">Dewpoint: 
&#160;13 F.</td></tr>
<tr><td align="left" class="big">Relative Humidity: 
&#160;62%</td></tr>
<tr><td align="left" class="big">Pressure: 
&#160;30.64 inches</td></tr>
<tr><td align="left" class="big">Heat Index: 
&#160;Not Applicable</td></tr>
<tr><td align="left" class="big">Wind Chill: 
&#160;12</td></tr>
<tr><td align="left" class="big">Sunrise: 
&#160;0711 CST</td></tr>
<tr><td align="left" class="big">Sunset: 
&#160;1701 CST</td></tr>
</table></td>
<td align="left" class="big">
<b>Twenty-Four Hour Summary</b><p></p>
<dl>
<dt align="center">Temperature: μ = 24.33, 
σ = 5.58</dt>
<p></p>
<dt align="center">Pressure: μ = 30.43,
σ = 0.20</dt>
</dl>
</td>
</tr>
<tr>
<td align="left"><img src="temp.png"></td>
<td align="left"><img src="pres.png"></td>
</tr>
</table>
<hr>
<p></p>
<table align="center"><tr>
<th> - </th>
<th align="left">
<p></p>
<a href="forecast.html"><h4>CURRENT FORECAST</h4></a><p></p>
</th>
<th> ---------- </th>
<th align="center">
<a href="http://www.crh.noaa.gov/radar/latest/DS.p19r0/si.kpah.shtml"><h4> CURRENT RADAR</h4></a><p></p>
</th>
<th> ---------- </th>
<th align="right">
<a href="http://www.rap.ucar.edu/weather/satellite/latest_EVV.jpg"><h4> CURRENT SATELLITE</h4></a><p></p>
</th>
<th> - </th>
</tr></table>
<p></p>
<hr>
Data from 
<a href="http://weather.noaa.gov/weather/current/KMDH.html"><font color="darkblue">The National Weather Service.</font></a>
</body>
</html>
